name: my_CI_workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  build_and_test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.9", "3.11"]
      fail-fast: false
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build and install
      run: pip install --verbose ".[test]"

    - name: Run tests
      run: |
        pytest -v --cov --cov-report xml balls_in_bins/_tests

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-black@v1
        with:
          black_args: "balls_in_bins/ --check"
          fail_on_error: "true"

  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8_py3'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
